require("plugins")
require("settings")
require("mappins")
require("config.colorscheme")
require("config._telescope")
require("config.cmp")
require("config.nvim-tree")
require("config.lualine")
require("config.treesitter")
-- -- require("config.null-ls")
require("config.vim-visual-multi")
require("config.gitgutter")
require("config.autoclose-tag")
require("config.markdown-preview")
require("config.vim-hexokinase")
require("config._lspconfig")
require('config.lsp-signature')
require("config.indent-blankline")
